openapi: 3.0.0
info:
  title: data-api restful backend api
  version: 0.1.0

paths:
  /mock:
    get:
      summary: Mock endpoint for testing
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  test:
                    type: string

      x-amazon-apigateway-integration:
        requestTemplates:
          "application/json": "{\"statusCode\":200, \"body\":$input.json('$')}"
        responses:
          "2\\d{2}":
            statusCode: 200
            responseTemplates:
              "application/json": "{\"request\": $input.json('$')}"
          default:
            statusCode: 200
            responseTemplates:
              "application/json": $input.json('$')"
        passthroughBehavior: when_no_match
        type: mock
