AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A fully service integrated DynamoDB API

Parameters:
  Stage:
    Type: String
    AllowedValues: [Prod, QA, Dev]
  Stackname:
    Type: String
  ApiLogGroup:
    Description: The Existing API log group
    Default: NONE
    Type: String

Globals:
  Api:
    MinimumCompressionSize: 1000
    TracingEnabled: True
    AccessLogSetting:
      DestinationArn: !GetAtt APIGatewayLogGroup.Arn
      Format: '{
                  "request_id": "$context.requestId",
                  "request_time": "$context.requestTimeEpoch",
                  "integration_latency": "$context.integration.latency",
                  "ip": "$context.identity.sourceIp",
                  "resource": "$context.resourcePath",
                  "method": "$context.httpMethod",
                  "status": "$context.status",
                  "response_length": "$context.responseLength",
                  "response_error": "$context.error.messageString"
              }'

Resources:

# # # # API Definition # # #
#   DynamoApi:
#     Type: AWS::Serverless::Api
#     Properties:
#       Name: !Sub ${Stage}-${Stackname}-Api
#       StageName: !Sub ${Stage}

# # # Logging Space # # #
  APIGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    # Condition: CreateNewLogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/${Stage}-${Stackname}-Api"
      RetentionInDays: 7
