AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DAPI backend

Parameters:
  Stage:
    Type: String
    AllowedValues: [Prod, QA, Dev]
  Stackname:
    Type: String
  S3Bucket:
    Type: String
  SwaggerFile:
    Type: String
  ApiLogGroup:
    Description: The Existing API log group
    Default: NONE
    Type: String

Globals:
  Api:
    MinimumCompressionSize: 1000
    TracingEnabled: True
    # AccessLogSetting:
    #   DestinationArn: !GetAtt APIGatewayLogGroup.Arn
    #   Format: '{
    #               "request_id": "$context.requestId",
    #               "request_time": "$context.requestTimeEpoch",
    #               "integration_latency": "$context.integration.latency",
    #               "ip": "$context.identity.sourceIp",
    #               "resource": "$context.resourcePath",
    #               "method": "$context.httpMethod",
    #               "status": "$context.status",
    #               "response_length": "$context.responseLength",
    #               "response_error": "$context.error.messageString"
    #           }'

Resources:

# # # # API Definition # # #
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${Stage}-${Stackname}-Api
      StageName: !Sub ${Stage}
      Auth:
        ResourcePolicy:
          AwsAccountWhiteList: [!Ref AWS::AcountId]
          IpRangeBlacklist: ["66.249.73.86"]
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: !Sub ${SwaggerFile}

  ODS:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Stage}-${Stackname}-Table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

# # # Logging Space # # #
  # APIGatewayLogGroup:
  #   Type: AWS::Logs::LogGroup
  #   Properties:
  #     LogGroupName: !Sub "/aws/apigateway/${Stage}-${Stackname}-Api"
  #     RetentionInDays: 7
