AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A fully service integrated DynamoDB API

Parameters:
  Stage:
    Type: String
    AllowedValues: [Prod, QA, Dev]
  Stackname:
    Type: String
  ApiLogGroup:
    Description: The Existing API log group
    Default: NONE
    Type: String

# Conditions:
#   CreateNewLogGroup: !Equals [!Ref ApiLogGroup, NONE]

Resources:

    # Storage Resource
  JobTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Stackname}-TestTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: LSI1
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: LSI1
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: LSI1
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: sk
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY

# # # Logging Space # # #
#   APIGatewayLogGroup:
#     Type: AWS::Logs::LogGroup
#     Condition: CreateNewLogGroup
#     Properties:
#       LogGroupName: !Sub "/aws/apigateway/${Stage}-${Stackname}-Api"
#       RetentionInDays: 14
