version: 2.1

orbs:
  aws-sam: circleci/aws-sam-serverless@2.1.0


jobs:

  sam-build-deploy:
    executor: aws-sam/default
    environment:
      AWS_DEFAULT_REGION: us-west-2
      STAGE: Dev
      STACKNAME: data-api
      S3_BUCKET: fraycorp-deployment-artifacts
    steps:
      - checkout
      - run: BUILD_ID=`echo $(date --iso-8601=seconds)`
      - aws-sam/install:
          profile-name: circleci

      - aws-sam/deploy:
          context: aws-personal
          stack-name: data-api
          template: template.yaml
          s3-bucket: fraycorp-deployment-artifacts
          parameter-overrides: |
            ParameterKey=Stage,ParameterValue=${STAGE}
            ParameterKey=Stackname,ParameterValue=${STACKNAME}
            ParameterKey=S3Bucket,ParameterValue=${S3_BUCKET}
          no-fail-onempty-changeset: true
          profile-name: circleci

      # - run:
      #     command: |
      #       sam deploy \
      #           --stack-name $STACKNAME \
      #           --s3-bucket $S3_BUCKET \
      #           --capabilities CAPABILITY_IAM \
      #           --parameter-overrides \
      #               ParameterKey=Stage,ParameterValue=${STAGE} \
      #               ParameterKey=Stackname,ParameterValue=${STACKNAME} \
      #               ParameterKey=S3Bucket,ParameterValue=${S3_BUCKET} \
      #           --profile circleci

# workflows:
  build-on-push:
    jobs:
      - sam-build-deploy
