version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1
  aws-sam: circleci/aws-sam-serverless@2.1.0
  # aws-s3: circleci/aws-s3@2.0.0

jobs:

  # Configure AWS profile
  aws-cli-setup:
    executor: aws-cli/default
    environment:
      AWS_DEFAULT_REGION: us-west-2
      STAGE: Dev
      STACKNAME: data-api
      S3_BUCKET: fraycorp-deployment-artifacts
    steps:
      - run: BUILD_ID=`uuidgen`
      - aws-cli/setup:
          profile-name: circleci
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY

  # Install SAM CLI
  install-sam:
    executor: aws-sam/default
    steps:
      - sam/install

  sam-build-deploy:
    executor: aws-sam/default
    steps:
      - checkout
      - run: |
          sam deploy \
              --stack-name $STACKNAME \
              --s3-bucket $S3_BUCKET \
              --s3-prefix $STACKNAME/$STAGE/$BUILD_ID \
              --capabilities CAPABILITY_IAM \
              --parameter-overrides \
                  ParameterKey=Stage,ParameterValue=${STAGE} \
                  ParameterKey=Stackname,ParameterValue=${STACKNAME} \
                  ParameterKey=S3Bucket,ParameterValue=${S3_BUCKET} \
              --profile-name circleci


  # Run unit tests
  unit-test:
    executor: sam/default
    steps:
      - run: echo "ADD UNIT TESTS"

  # Run smoke tests
  smoke-test:
    executor: sam/default
    steps:
      - run: echo "ADD SMOKE TESTS"


workflows:
  build-on-push:
    jobs:
      - aws-cli-setup:
          context: aws-personal

      - install-sam:
          name: install SAM

      - sam-build-deploy:
          name: build deploy

