version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1
  aws-sam: circleci/aws-sam-serverless@2.1.0
  # aws-s3: circleci/aws-s3@2.0.0

jobs:

  aws-sam-config:
    executor: aws-sam/default
    environment:
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - aws-sam/install:
          profile-name: circleci
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY

  sam-build-deploy:
    executor: aws-sam/default
    environment:
      STAGE: Dev
      STACKNAME: data-api
      S3_BUCKET: fraycorp-deployment-artifacts
    steps:
      - checkout
      - run: BUILD_ID=`date +"%Y-%m-%dT%T"`
      - run: |
          sam deploy \
              --stack-name $STACKNAME \
              --s3-bucket $S3_BUCKET \
              --s3-prefix $STACKNAME/$STAGE/$BUILD_ID \
              --capabilities CAPABILITY_IAM \
              --parameter-overrides \
                  ParameterKey=Stage,ParameterValue=${STAGE} \
                  ParameterKey=Stackname,ParameterValue=${STACKNAME} \
                  ParameterKey=S3Bucket,ParameterValue=${S3_BUCKET} \
              --profile-name circleci

  # Run unit tests
  unit-test:
    executor: sam/default
    steps:
      - run: echo "ADD UNIT TESTS"

  # Run smoke tests
  smoke-test:
    executor: sam/default
    steps:
      - run: echo "ADD SMOKE TESTS"

workflows:
  build-on-push:
    jobs:

      - aws-cli-setup:
          context: aws-personal

          - install-sam:
              requires:
                - aws-cli-setup

      - sam-build-deploy:
          requires:
            - install-sam